# Konfiguracja syslog-ng

# Source zostaje jak jest

###########################
# Destination
###########################
# destination - oznacza gdzie mają trafić logi

# nazwa konfiguracji
destination d_logserver {
    # oznacza że logi mają wędrować do sieci
    network(
        # adres IP serwera logów
        "192.168.66.4"
        # używa protokołu tcp
        transport("tcp")
        # używa portu 514
        port(514)
    );
};

###########################
# Log
###########################
# log - łączy source z destination, bez tej sekcji syslog-ng by nie działał

# definiuje przepływ logów: skąd są pobierane i gdzie wysyłane
log {
    # źródło logów (lokalne logi systemowe)
    source(s_src);
    # Wysyła do centralnego serwera logów
    destination(d_logserver);
}
