#=====================================#
#              NASŁUCH                #
#=====================================#
# Nasłuchuje połączenia
listen=YES
# wyłącza ipv6
listen_ipv6=NO

#=====================================#
#       ANONYMOUS  (PUBLICZNY)        #
#=====================================#
# pozwala gością logować się jako anonymous
anonymous_enable=YES
# katalog dla anonymous
anon_root=/srv/share/ftp/public
# anonymous nie może wrzucać plików
anon_upload_enable=NO
# anonymous nie może tworzyć katalogów
anon_mkdir_write_enable=NO

#=====================================#
#       UŻYTKOWNICY LOKALNI           #
#=====================================#
# użytkownicy systemiwi mogą się logować
local_enable=YES
# użytkownicy lokalni mogą zapisywać pliki
write_enable=YES

#=====================================#
#           BEZPIECZEŃSTWO            #
#=====================================#
# użytkownik ma dostęp tylko do swojego katalogu
chroot_local_user=YES
# pozwala pisać tylko w katalogu chroot, bez tego 
allow_writable_chroot=YES
# specjalny pusty katalog do izolacji

secure_chroot_dir=/var/run/vsftpd/empty
# ukrywa UID/GID
hide_ids=YES

#=====================================#
#            UPRAWNIENIA              #
#=====================================#
# ustawia prawa do plików (rw-r--r--)
local_umask=022

#=====================================#
#               LOGI                  #
#=====================================#
# używa lokalnego czasu
use_localtime=YES
# loguje transfery plików
xferlog_enable=YES
# loguje wszystko np. połączenia, komendy
log_ftp_protocol=YES
# pokazuje komunikat z plików .message w 
dirmessage_enable=YES

#=====================================#
#               SSL                   #
#=====================================#
# brak szyfrowania
ssl_enable=NO                                   # brak szyfrowania

#=====================================#
#             SIEĆ (FTP)              #
#=====================================#
 # włącza tryb pasywny 
pasv_enable=YES
# zakres portów danych
pasv_min_port=10000
#  zakres portów danych
pasv_max_port=10100
# używa portu 20 do danych
connect_from_port_20=YES

#=====================================#
#               SSL                   #
#=====================================#
# używa pam (logowanie systemowe linuxa)
pam_service_name=vsftpd
# używa listy użytkowników
userlist_enable=YES
# plik z użytkownikami
userlist_file=/etc/vsftpd.userlist
# tylko ci użytkownicy mogą się logować
userlist_deny=NO
