#=====================================#
#              NASŁUCH                #
#=====================================#
listen=YES                                      # Nasłuchuje połączenia
listen_ipv6=NO                                  # wyłącza ipv6

#=====================================#
#       ANONYMOUS  (PUBLICZNY)        #
#=====================================#
anonymous_enable=YES                            # pozwala gością logować się jako anonymous
anon_root=/srv/share/ftp/public                 # katalog dla anonymous
anon_upload_enable=NO                           # anonymous nie może wrzucać plików
anon_mkdir_write_enable=NO                      # anonymous nie może tworzyć katalogów

#=====================================#
#       UŻYTKOWNICY LOKALNI           #
#=====================================#
local_enable=YES                                # użytkownicy systemiwi mogą się logować
write_enable=YES                                # użytkownicy lokalni mogą zapisywać pliki

#=====================================#
#           BEZPIECZEŃSTWO            #
#=====================================#
chroot_local_user=YES                           # użytkownik ma dostęp tylko do swojego                                                                                               katalogu
allow_writeable_chroot=YES                      # pozwala pisać tylko w katalogu chroot, bez tego                                                                                 często FTP nie działa
secure_chroot_name=/var/run/vsftpd/empty        # specjalny pusty katalog do izolacji
hide_ids=YES                                    # ukrywa UID/GID

#=====================================#
#            UPRAWNIENIA              #
#=====================================#
local_umask=022                                 # ustawia prawa do plików (rw-r--r--)

#=====================================#
#               LOGI                  #
#=====================================#
use_localtime=YES                               # używa lokalnego czasu
xferlog_enable=YES                              # loguje transfery plików
log_ftp_protocol=YES                            # loguje wszystko np. połączenia, komendy
dirmessage_enable=YES                           # pokazuje komunikat z plików .message w                                                                                           katalogach


#=====================================#
#               SSL                   #
#=====================================#
ssl_enable=NO                                   # brak szyfrowania

#=====================================#
#             SIEĆ (FTP)              #
#=====================================#
pasv_enable=YES                                 # włącza tryb pasywny 
pasv_min_port=10000                             # zakres portów danych
pasv_max_port=10100                             #  zakres portów danych
connect_from_port_20=YES                        # używa portu 20 do danych

#=====================================#
#               SSL                   #
#=====================================#
pam_service_name=vsftpd                         # używa pam (logowanie systemowe linuxa)
userlist_enable=YES                             # używa listy użytkowników
userlist_file=/etc/vsftpd.userlist              # plik z użytkownikami
userlist_deny=NO                                # tylko ci użytkownicy mogą się logować

