Samba

## Dodaj na końcu pliku.
[publiczny]                                       # Nazwa widoczna w sieci
   path = /srv/samba/publiczny                    # Ścieżka do katalogu samba
   comment = Publiczny katalog dla wszystkich     # Opis udziału
   browseable = yes                               # Jest widoczny dla użytkowników
   writable = yes                                 # Można zapisywać pliki
   guest ok = yes                                 # Połączenie bez podawania hasła
   guest only = yes                               # Wymusza łączenie się jako gość
   force user = nobody                            # Każdy użytkownik działa jak jeden wspólny
   force group = nobody                           # Przypisuje wszystkie tworzone pliki do jednej grupy
   create mask = 0660                             # Uprawnienia dla każdego nowego pliku
   directory mask = 0770                          # Uprawnienia dla każdego nowego folderu

[prywatny]                                        # Nazwa widoczna w sieci
   path = /srv/samba/prywatny                     # Ścieżka do katalogu samba
   comment = Prywatnt katalog                     # Opis udziału
   browseable = no                                # Nie jest widoczny dla użytkowników ale można się połączyć
   writable = yes                                 # Można zapisywać pliki
   guest ok = no                                  # Wymagane hasło
   valid users = klientsmb                        # Użytkownicy, którzy mogą się połączyć
   force user = klientsmb                         # Każdy zapisany plik należy do użytkownika klientsmb
   force group = klientsmb                        # Każdy zapisany plik należy do grupy klientsmb
   create mask = 0660                             # Uprawnienia dla każdego nowego pliku
   directory mask = 0770                          # Uprawnienia dla każdego nowego katalogu
   force create mode = 0660                       # Wymusza uprawnienia dla pliku niezależnie od klienta
   force directory mode = 0770                    # Wymusza uprawnienia dla katalogu niezależnie od klienta
