# Konfiguracja syslog-ng serwer4

# Dodaj to na początku odpowiedniej sekcji

#######################
# Sources
#######################
# source - definiuje skąd pochodzą logi

# nazwa źródła
source s_network {
    # oznacza że to źródło ma odbierać logi z sieci
    network(
      # używa protokołu tcp
      transport("tcp")
      # używa portu 514
      port(514)
    );
};

#######################
# Destination
#######################
# destination - oznacza gdzie mają trafić logi

# nazwa konfiguracji
destination d_central_logs {
    # zapisuje logi do zdefiniowanego pliku z datą
    # zmienna HOST --> tworzy katalog z nazwą hosta z którego przyszły logi
    # zmienna PROGRAM:-unknow --> zapisuje logi do pliku z nazwą programu, jeżeli nie może rozpoznać programu to zapisuje logi w pliku unknow
    file(/var/log/central/${HOST}/${YEAR}-${MONTH}-${DAY}_${PROGRAM:-unknow}.log
    # jeźeli katalog nie istnieje, utwórz go
    create_dirs(yes));
};

# nazwa konfiguracji dla ERROR LOGS
destination d_error_logs {
    # zapisuje logi do zdefiniowanego pliku z datą
    # zamienna HOST --> tworzy katalog z nazwą hosta z którego przyszły logi
    #
    file(/var/log/central/CRITICAL_ERROR/${HOST}/${YEAR}-${MONTH}-${DAY}_services-watchdog.log
    # jeźeli katalog nie istnieje, utwórz go
    create_dirs(yes));
  }

######################
# Filters
######################
# filter - służy do odsiewania logów

# tworzy filtr dla critical error
filter f_critical_error {
    # przepuszcza tylko tekst który zawiera CRITICAL_ERROR
    match("CRITICAL_ERROR");
  };

######################
# Log
######################
# log - łączy source z destination, bez tej sekcji syslog-ng by nie działał

# nazwa konfiguracji
log {
    # źródło logów (zbiera logi z całej sieci na porcie 514)
    source(s_network);
    # logi są wysyłane do wyznaczonej ścieżki w "Destination"
    destination(d_central_logs);
}

# nazwa konfiguracji dla error logs
log {
    # źródło logów (zbiera logi z całej sieci na porcie 514)
    source(s_network);
    # filtruje logi
    filter(f_critical_error);
    # logi są wysyłane do wyznaczonej ścieżki w "Destination"
    destination(f_critical_error);
  };
