#=======================================#
#         Konfiguracja DHCP             #
#=======================================#

authoritative;

# Domyślny czas dzierżawy IP w sekundach
default-lease-time 600;
# Maksymalny czas dzierżawy IP w sekundach
max-lease-time 7200;

# Zakres adresów przydzielanych hostom
subnet 192.168.66.0 netmask 255.255.255.0 {
    range 192.168.66.50 192.168.66.100;         # Zakres DHCP
    option routers 192.168.66.0;                # Brama Domyślna
    option domain-name-servers 192.168.66.1;    # DNS
    option broadcast-address 192.168.66.255;    # Adres broadcast
  }

# Rezerwacja adresu ip
host klient1 {                                  # Nazwa hosta
    hardware ethernet 52:54:00:45:66:b2;        # Adres MAC hosta
    fixed-address 192.168.66.49;                # Przypisany i stały adres IP
  }
