Apache

<VirtualHost *:80>                                              # Strona otwiera się na porcie 80
  ServerName www.lab.local                                      # Nazwa strony
  ServerAlias lab.local                                         # Alias strony
  DocumentRoot /var/www/www.lab.local                           # Ścieżka do katalogu strony

  # Logi
  ErrorLog ${APACHE_LOG_DIR}/www.lab.local_error.log            # Logi błędów
  CustomLog ${APACHE_LOG_DIR}/www.lab.local_access.log          # Logi wizyt i żądań HTML

  # Ustawienia katalogu strony
  <Directory /var/www/www.lab.local>
    Options FollowSymLinks                                      # Zezwala na podążanie za linkami symbolicznymi
    AllowOverride None                                          # htaccess nie działa
    Require all granted                                         # Dostęp dla wszystkich
  </Directory>

    DirectoryIndex index.html                                   # Domyślny plik strony
</VirtualHost>
